CREATE TABLE Receive (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  MSG_ID TEXT NOT NULL,
  TYPE TEXT NOT NULL,
  MEMBER TEXT NOT NULL,
  CONTENT TEXT NOT NULL
);

CREATE TABLE Send (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  TYPE TEXT NOT NULL,
  CONTENT TEXT NOT NULL
);
