CREATE TABLE Receive (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  MSG_ID TEXT NOT NULL,
  TYPE TEXT NOT NULL,
  MEMBER TEXT NOT NULL,
  CONTENT TEXT NOT NULL
);

CREATE TABLE Send (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  TYPE TEXT NOT NULL,
  CONTENT TEXT NOT NULL
);

CREATE TABLE DebitCard (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  BANK TEXT NOT NULL,
  NUMBER TEXT NOT NULL,
  OWNER TEXT NOT NULL,
  AMOUNT REAL NOT NULL
);

CREATE TABLE CreditCard (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  BANK TEXT NOT NULL,
  NUMBER TEXT NOT NULL,
  OWNER TEXT NOT NULL,
  AMOUNT REAL NOT NULL,
  BILL_DATE INTEGER NOT NULL,
  REPAYMENT_DATE INTEGER NOT NULL
);

CREATE TABLE Mortgage (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  LOCATION TEXT NOT NULL,
  AMOUNT REAL NOT NULL,
  REPAYMENT_DATE INTEGER NOT NULL
);

CREATE TABLE AutoLoan (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  CAR TEXT NOT NULL,
  AMOUNT REAL NOT NULL,
  REPAYMENT_DATE INTEGER NOT NULL
);